### PR TITLE
Bump to Spring Boot 2.3

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@pavolloffay I got some kind of failure when trying to do a release with this commit, see: https://travis-ci.org/github/opentracing-contrib/java-spring-tracer-configuration/builds/729291292

Is there something that you or I need to setup for this? Last time I tried it (a few months ago it worked fine)

**Comment by geoand** [comment]
@pavolloffay I still can't release:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project opentracing-spring-tracer-configuration-parent: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] remote: Invalid username or password.
[ERROR] fatal: Authentication failed for 'https://%24%7Benv.GH_USER%7D:[secure]@github.com/opentracing-contrib/java-spring-tracer-configuration.git/'
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Any idea what's going on?

**Comment by pavolloffay** [comment]
It seems the auth failed, I will try to reencrypt credentials and release.

**Comment by geoand** [comment]
Thanks

**Comment by geoand** [comment]
@pavolloffay any update with this?

**Comment by pavolloffay** [comment]
I am on it

**Comment by pavolloffay** [comment]
I have reencrypted keys and cut another release.

**Comment by geoand** [comment]
Great, thanks for your help @pavolloffay

**Pull request merged**
